### ISSUE TITLE
Getting Error From Slack/Google API When Connecting

### ISSUE THREAD

**Issue by theskyfloor** [dukt/craft-slack#1]
Error I am getting is no scope provided:

OAuth error: blank_scope: Requested scopes cannot be blank

Any ideas? Should I be defining scopes somewhere in the plug-in source?

**Comment by benjamindavid** [comment]
Which plugin are you trying to connect with ? REST or Social Login ?

**Comment by theskyfloor** [comment]
REST is the Slack plug-in built for Social Login?

**Comment by benjamindavid** [comment]
Social Login allows you to login to web services (including Stripe)

REST is useful for performing authenticated requests on web services (including Stripe)

Social Login and REST only come with Google, Facebook and Twitter providers built-in, so you have to install Craft Slack plugin in order to use Slack with those plugins.
